// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetapi.Data;

#nullable disable

namespace aspnetapi.Data.Migrations
{
    [DbContext(typeof(StockContextDB))]
    [Migration("20221110183914_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("aspnetapi.Data.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("TEXT");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("StockId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            StockId = 1,
                            Country = "Stock 1 country",
                            Data = "Stock 1 was bought on 2022.11.11",
                            Price = "Stock 1 price",
                            StockName = "Stock 1 name"
                        },
                        new
                        {
                            StockId = 2,
                            Country = "Stock 2 country",
                            Data = "Stock 2 was bought on 2022.11.11",
                            Price = "Stock 2 price",
                            StockName = "Stock 2 name"
                        },
                        new
                        {
                            StockId = 3,
                            Country = "Stock 3 country",
                            Data = "Stock 3 was bought on 2022.11.11",
                            Price = "Stock 3 price",
                            StockName = "Stock 3 name"
                        },
                        new
                        {
                            StockId = 4,
                            Country = "Stock 4 country",
                            Data = "Stock 4 was bought on 2022.11.11",
                            Price = "Stock 4 price",
                            StockName = "Stock 4 name"
                        },
                        new
                        {
                            StockId = 5,
                            Country = "Stock 5 country",
                            Data = "Stock 5 was bought on 2022.11.11",
                            Price = "Stock 5 price",
                            StockName = "Stock 5 name"
                        },
                        new
                        {
                            StockId = 6,
                            Country = "Stock 6 country",
                            Data = "Stock 6 was bought on 2022.11.11",
                            Price = "Stock 6 price",
                            StockName = "Stock 6 name"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
